# All these parameters have to be fixed according to the specs. detailed in 852_Echo_Sounder_Kit_manual.pdf
# profundidad_minima --> eco sounder kit manual, pg 23: Byte 15 Profile Minimum Range Minimum range for profile point digitization
# 0 – 250  0 to 25 meters in 0.1 meter increments
# Byte 15 = min range in meters / 10
# profundidad_maxima ==> //Range: 5,10,20,30,40,50 in meters. Defined in the technical specs of the manufacturer 
# Start Gain: 0 to 40dB in 1 dB increments,
# longitud_pulso --> Byte 14 Pulse Length, Length of acoustic transmit pulse. 1-255. 1 to 255 micro sec in 1 micro sec increments
# The external trigger must be a 0 to 5 volt TTL pulse with a minimum length of 100 microseconds.
# Switch Delay: The echo sounder can be commanded to pause (from 0 to 510 msec). Before sending its return data to allow the commanding program enough time to setup for serial reception of the return data.
# 0 to 255 in 2 msec increments Byte 24 = delay_in_milliseconds/2 . Do not use a value of 253!
# //Data Points: 25=250 points 'IMX'
# timeoutSerial : timeout of the serial port, integer
# timerDuration: time between timer interruptions. Decimal, in seconds. The timer check outs the serial port, introduces the input frame and waits for the inpunt data. 
# timerDuration is the period between calls to the timer callback. For example, if this is ros::Duration(0.1), the callback will be scheduled for every 1/10th of a second
# range_percentage is the percentage over the current range that the difference between previous and current ranges represents
# if the difference between the current and the previous range represents a percentage over the current range greater than 
# this value, the new range will not be published. 

# imagenex_echosounder/range: 10.0 # Range: 5,10,20,30,40,50 in meters
# imagenex_echosounder/profile_minimum_range: 1 #profile_minimum_range in meters # 0 - 250 / 10
# imagenex_echosounder/gain: 14
# imagenex_echosounder/pulse_length: 100
# imagenex_echosounder/delay: 2
# imagenex_echosounder/data_points: 25
# imagenex_echosounder/profile: 1
# imagenex_echosounder/absorption: 20
# imagenex_echosounder/timeoutSerial: 1
# imagenex_echosounder/timerDuration: 0.2
# magenex_echosounder/range_percentage: 20
# imagenex_echosounder/sample_vector_size: 10

imagenex_echosounder:
  range: 5.0 # Range: 5,10,20,30,40,50 in meters
  profile_minimum_range: 0.5
  gain: 14
  pulse_length: 100
  delay: 2
  data_points: 25
  profile: 1
  absorption: 20
  timeoutSerial: 1
  timerDuration: 0.2
  range_percentage: 20
  sample_vector_size: 20
  devname: "/dev/serial/by-id/usb-FTDI_Chipi-X_FT5ADULG-if00-port0"
  # devname: "/dev/serial/by-id/usb-FTDI_UT232R_FT2D3911-if00-port0"



imagenex_echosounder_2:
  range: 5.0 # Range: 5,10,20,30,40,50 in meters
  profile_minimum_range: 0.5
  gain: 14
  pulse_length: 100
  delay: 2
  data_points: 25
  profile: 1
  absorption: 20
  timeoutSerial: 1
  timerDuration: 0.2
  range_percentage: 20
  sample_vector_size: 20
  devname: "/dev/serial/by-id/usb-FTDI_Chipi-X_FT5ADULG-if00-port0"


